### ISSUE TITLE
Playlist does not show video details (1.9.2)

### ISSUE THREAD

**Issue by raelb** [Tyrrrz/YoutubeDownloader#263]
### Version

1.9.2

### Details

Download list does not show any video details as before:

![image](https://user-images.githubusercontent.com/13108198/168591115-9d240d24-e101-4e71-9357-5f3e80f734f8.png)

### Steps to reproduce

- Enter playlist url into edit box
- select multiple videos
- I selected to save as mp3

**Comment by Tyrrrz** [comment]
Can't reproduce this one. What playlist were you downloading? Maybe the window is too small?

**Comment by raelb** [comment]
I tried again. When only selecting a small number e.g. 5, it does not occur. But if I select larger number e.g. 30, then it occurs. 
e.g. https://www.youtube.com/playlist?list=PLillGF-RfqbZ2ybcoD2OaabW2P7Ws8CWu

Btw, I am on scaling = 150%. That may have to do with it...

**Comment by Tyrrrz** [comment]
Yeah try without the scaling or try making the window bigger

**Comment by raelb** [comment]
I tried with no scaling (i.e. 100%). The bug still occurs. See video:

https://user-images.githubusercontent.com/13108198/168698918-f942a149-cef4-47aa-8515-4e20d7ca5582.mp4

**Comment by Tyrrrz** [comment]
That's weird, but at least I see it restores after resizing the window. Does it always lag like that or is it just during recording?

**Comment by raelb** [comment]
Sorry, the lag was from virtual machine not due to your app

**Comment by Tyrrrz** [comment]
Potentially fixed by updating dependencies. Please try the latest CI build and see if it works. If it doesn't feel free to reopen the issue.
https://github.com/Tyrrrz/YoutubeDownloader/actions/workflows/main.yml

**Comment by raelb** [comment]
Where is the exe located in ci build? Edit: nevermind, found it

**Comment by raelb** [comment]
No, I'm afraid problem still occurs. Not a big issue since I can fix by drag the window small then large again.

**Comment by Tyrrrz** [comment]
Sad. I was hoping it would get fixed by updating UI-related packages.
